// Academic Word List (AWL) — Coxhead 2000
// 570 word families in 10 sub-lists; here we cover the most IELTS-relevant.

export type AWLSublist = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10

export type QuestionType = 'gap_fill' | 'definition_match' | 'word_form'

export interface AWLQuestion {
  id: string
  sublist: AWLSublist
  headword: string          // base word family member
  type: QuestionType
  // gap_fill: a sentence with {{gap}} placeholder
  // definition_match: multiple choice — choose correct definition
  // word_form: choose correct form (noun/verb/adjective/adverb)
  sentence?: string         // for gap_fill and word_form
  options: string[]         // always 4 options
  answer: string
  definition: string        // always provided for reference
  explanation: string
  domain: string            // e.g. "academic", "science", "economics"
}

export const AWL_QUESTIONS: AWLQuestion[] = [

  // ─── Sublist 1 (Most frequent) ────────────────────────────────

  {
    id: 'awl_01_analyse',
    sublist: 1,
    headword: 'analyse',
    type: 'gap_fill',
    sentence: 'Researchers carefully {{gap}} the data before drawing any conclusions.',
    options: ['analysed', 'analysing', 'analysis', 'analytical'],
    answer: 'analysed',
    definition: 'to examine something in detail in order to understand it better',
    explanation: 'After "carefully" we need a past tense verb: "analysed". "Analysis" is a noun; "analytical" is an adjective.',
    domain: 'academic',
  },
  {
    id: 'awl_01_approach',
    sublist: 1,
    headword: 'approach',
    type: 'definition_match',
    options: [
      'to make something easier to understand',
      'a way of dealing with or thinking about something',
      'the result of a scientific experiment',
      'a formal written report',
    ],
    answer: 'a way of dealing with or thinking about something',
    definition: 'a way of dealing with or thinking about something',
    explanation: '"Approach" as a noun = a method or strategy. "The study used a qualitative approach."',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_01_concept',
    sublist: 1,
    headword: 'concept',
    type: 'gap_fill',
    sentence: 'The {{gap}} of sustainable development has become central to modern economics.',
    options: ['concept', 'conception', 'conceptual', 'conceptually'],
    answer: 'concept',
    definition: 'an abstract idea or general understanding of something',
    explanation: '"The concept of X" = the idea or notion of X. "Conception" is slightly different (an idea or belief). "Conceptual" is an adjective.',
    domain: 'academic',
  },
  {
    id: 'awl_01_context',
    sublist: 1,
    headword: 'context',
    type: 'gap_fill',
    sentence: 'The meaning of a word can only be understood in its cultural {{gap}}.',
    options: ['context', 'content', 'contrast', 'conduct'],
    answer: 'context',
    definition: 'the circumstances or setting in which something occurs or is understood',
    explanation: '"In its context" = within the surrounding situation. Do not confuse with "content" (= what something contains).',
    domain: 'language',
  },
  {
    id: 'awl_01_establish',
    sublist: 1,
    headword: 'establish',
    type: 'word_form',
    sentence: 'The research sought to {{gap}} a clear link between diet and cognitive decline.',
    options: ['establish', 'establishment', 'established', 'establishing'],
    answer: 'establish',
    definition: 'to start, create, or prove something firmly',
    explanation: '"Sought to establish" — after "to" (infinitive), use the base form: "establish". "Sought to established" is incorrect.',
    domain: 'academic',
  },
  {
    id: 'awl_01_evidence',
    sublist: 1,
    headword: 'evidence',
    type: 'definition_match',
    options: [
      'a logical argument supporting a point of view',
      'facts or information that help to prove something is true',
      'the conclusion of a research study',
      'a statistical measurement of data',
    ],
    answer: 'facts or information that help to prove something is true',
    definition: 'facts or information that help to prove something is true',
    explanation: '"Evidence" is uncountable: "the evidence shows", not "the evidences show". Collocations: "provide evidence", "evidence suggests", "empirical evidence".',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_01_factor',
    sublist: 1,
    headword: 'factor',
    type: 'gap_fill',
    sentence: 'Poverty is one of the most significant {{gap}} contributing to poor health outcomes.',
    options: ['factors', 'features', 'functions', 'findings'],
    answer: 'factors',
    definition: 'one of several elements that influence or cause a result',
    explanation: '"Factors contributing to" = causes or elements. "One of the most significant factors" — plural after "one of the most...".',
    domain: 'science',
  },
  {
    id: 'awl_01_function',
    sublist: 1,
    headword: 'function',
    type: 'gap_fill',
    sentence: 'The liver {{gap}} as a filter, removing toxins from the bloodstream.',
    options: ['functions', 'functioned', 'functional', 'functioning'],
    answer: 'functions',
    definition: 'to work or operate in a particular way; the purpose or role of something',
    explanation: '"Functions as" = acts as, serves the role of. Present simple for permanent facts: "functions". "Functional" is an adjective.',
    domain: 'science',
  },
  {
    id: 'awl_01_impact',
    sublist: 1,
    headword: 'impact',
    type: 'word_form',
    sentence: 'Climate change has had a profound {{gap}} on global food security.',
    options: ['impact', 'impacted', 'impactful', 'impacting'],
    answer: 'impact',
    definition: 'a powerful effect on someone or something',
    explanation: '"A profound impact on" — "impact" is used as a noun here. "Have an impact on" is the standard collocation.',
    domain: 'environment',
  },
  {
    id: 'awl_01_indicate',
    sublist: 1,
    headword: 'indicate',
    type: 'gap_fill',
    sentence: 'The survey results {{gap}} that public confidence in government has declined.',
    options: ['indicate', 'indication', 'indicative', 'indicated'],
    answer: 'indicate',
    definition: 'to show, point to, or be a sign that something is true',
    explanation: '"The results indicate that" = present simple for academic reporting of current findings. "Indicated" (past) would imply a completed study.',
    domain: 'academic',
  },

  // ─── Sublist 2 ────────────────────────────────────────────────

  {
    id: 'awl_02_achieve',
    sublist: 2,
    headword: 'achieve',
    type: 'word_form',
    sentence: 'The government set ambitious targets, but their actual {{gap}} remained limited.',
    options: ['achieve', 'achievement', 'achievable', 'achieved'],
    answer: 'achievement',
    definition: 'something that has been accomplished, especially through effort',
    explanation: '"Actual achievement" — noun needed after the possessive "their". "Achieve" is a verb; "achievement" is the nominalised form.',
    domain: 'academic',
  },
  {
    id: 'awl_02_conclude',
    sublist: 2,
    headword: 'conclude',
    type: 'gap_fill',
    sentence: 'Based on the available evidence, we can {{gap}} that the intervention was effective.',
    options: ['conclude', 'conclusion', 'conclusive', 'conclusively'],
    answer: 'conclude',
    definition: 'to reach a judgement or decision after consideration of evidence',
    explanation: '"We can conclude that" — after modal "can", use base form. "Conclusion" is the noun form.',
    domain: 'academic',
  },
  {
    id: 'awl_02_data',
    sublist: 2,
    headword: 'data',
    type: 'definition_match',
    options: [
      'written documents produced for academic purposes',
      'facts, statistics, or information collected for reference or analysis',
      'conclusions drawn from a research study',
      'methods used to gather information',
    ],
    answer: 'facts, statistics, or information collected for reference or analysis',
    definition: 'facts, statistics, or information collected for reference or analysis',
    explanation: '"Data" is technically plural (datum = singular) but widely treated as uncountable in modern academic English: "the data suggests" is now acceptable.',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_02_environmental',
    sublist: 2,
    headword: 'environmental',
    type: 'gap_fill',
    sentence: 'The factory was closed after it was found to have caused significant {{gap}} damage.',
    options: ['environmental', 'environment', 'environmentally', 'environments'],
    answer: 'environmental',
    definition: 'relating to the natural world and the impact of human activity on it',
    explanation: '"Environmental damage" — adjective before noun. "Environment" is a noun; "environmentally" is an adverb.',
    domain: 'environment',
  },
  {
    id: 'awl_02_significant',
    sublist: 2,
    headword: 'significant',
    type: 'gap_fill',
    sentence: 'There was no statistically {{gap}} difference between the two groups.',
    options: ['significantly', 'significant', 'significance', 'signify'],
    answer: 'significant',
    definition: 'important or large enough to have a noticeable effect',
    explanation: '"Statistically significant" — adverb + adjective: "statistically" modifies the adjective "significant". Note: "significantly" would modify a verb.',
    domain: 'academic',
  },

  // ─── Sublist 3 ────────────────────────────────────────────────

  {
    id: 'awl_03_alternative',
    sublist: 3,
    headword: 'alternative',
    type: 'gap_fill',
    sentence: 'Solar energy provides a clean {{gap}} to fossil fuels.',
    options: ['alternative', 'alteration', 'alternation', 'altercation'],
    answer: 'alternative',
    definition: 'one of two or more available possibilities; something that can be chosen instead',
    explanation: '"An alternative to X" = something you can use instead of X. "Alteration" = a change; "altercation" = a noisy argument.',
    domain: 'environment',
  },
  {
    id: 'awl_03_component',
    sublist: 3,
    headword: 'component',
    type: 'definition_match',
    options: [
      'the main subject of a report',
      'a part or element of something larger',
      'the relationship between two variables',
      'a method of organising data',
    ],
    answer: 'a part or element of something larger',
    definition: 'a part or element of a larger whole, especially of a machine or system',
    explanation: '"A key component of the system" = an essential part. Collocates with: "critical", "essential", "key", "core" component.',
    domain: 'technical',
    sentence: undefined,
  },
  {
    id: 'awl_03_emphasise',
    sublist: 3,
    headword: 'emphasise',
    type: 'gap_fill',
    sentence: 'The report {{gap}} the urgent need for policy reform.',
    options: ['emphasises', 'emphasis', 'emphatic', 'emphatically'],
    answer: 'emphasises',
    definition: 'to give special importance or attention to something',
    explanation: '"The report emphasises" — present simple, third person singular. "Emphasis" is the noun; "emphatic" is an adjective.',
    domain: 'academic',
  },
  {
    id: 'awl_03_policy',
    sublist: 3,
    headword: 'policy',
    type: 'gap_fill',
    sentence: 'The government introduced a new economic {{gap}} designed to reduce unemployment.',
    options: ['policy', 'politics', 'political', 'politician'],
    answer: 'policy',
    definition: 'a course of action or set of principles adopted by an organisation or government',
    explanation: '"Economic policy" = a planned set of actions. Do not confuse with "politics" (the activity of governing). "Policy" collocates with: implement, adopt, introduce, set.',
    domain: 'economics',
  },

  // ─── Sublist 4 ────────────────────────────────────────────────

  {
    id: 'awl_04_access',
    sublist: 4,
    headword: 'access',
    type: 'gap_fill',
    sentence: 'Children in rural areas often lack {{gap}} to quality healthcare.',
    options: ['access', 'accessible', 'accessing', 'accessed'],
    answer: 'access',
    definition: 'the ability or right to use or reach something',
    explanation: '"Lack access to" — "access" as a noun here. Collocations: "have access to", "gain access to", "deny access to".',
    domain: 'social',
  },
  {
    id: 'awl_04_adequate',
    sublist: 4,
    headword: 'adequate',
    type: 'definition_match',
    options: [
      'more than enough for a particular purpose',
      'satisfactory or acceptable; enough for a purpose',
      'exactly the right amount, not too much or too little',
      'unusually high in quality',
    ],
    answer: 'satisfactory or acceptable; enough for a purpose',
    definition: 'satisfactory or acceptable in quality or quantity; enough for a purpose',
    explanation: '"Adequate" ≠ "excellent". It means "sufficient" — meeting the minimum standard. "Adequate funding" = enough funding, though not necessarily generous.',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_04_regulate',
    sublist: 4,
    headword: 'regulate',
    type: 'word_form',
    sentence: 'Stricter {{gap}} of the financial sector is needed to prevent future crises.',
    options: ['regulate', 'regulatory', 'regulation', 'regulated'],
    answer: 'regulation',
    definition: 'a rule or directive made and maintained by an authority',
    explanation: '"Stricter regulation of" — noun needed after adjective "stricter". "Regulatory" is an adjective; "regulate" is a verb.',
    domain: 'economics',
  },

  // ─── Sublist 5 ────────────────────────────────────────────────

  {
    id: 'awl_05_albeit',
    sublist: 5,
    headword: 'albeit',
    type: 'definition_match',
    options: [
      'in addition to what has already been stated',
      'even though; although',
      'as a direct result of',
      'in contrast to what was expected',
    ],
    answer: 'even though; although',
    definition: 'even though; although (used to introduce a fact that partially contradicts what was just said)',
    explanation: '"The results were positive, albeit inconclusive." "Albeit" = although/even though. Formal academic connector — unlike "although", it does not start a clause; it precedes a noun phrase or adjective.',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_05_controversy',
    sublist: 5,
    headword: 'controversy',
    type: 'word_form',
    sentence: 'The proposal proved highly {{gap}}, dividing opinion among experts.',
    options: ['controversy', 'controversial', 'controversially', 'controversies'],
    answer: 'controversial',
    definition: 'causing a lot of disagreement or argument',
    explanation: '"Proved highly controversial" — adjective after "proved" (linking verb). "Controversy" is the noun; "controversially" is the adverb.',
    domain: 'academic',
  },
  {
    id: 'awl_05_implication',
    sublist: 5,
    headword: 'implication',
    type: 'gap_fill',
    sentence: 'The study has important {{gap}} for public health policy.',
    options: ['implications', 'implicates', 'implied', 'implying'],
    answer: 'implications',
    definition: 'a possible effect or consequence that is not directly stated',
    explanation: '"Implications for X" = consequences or what the findings mean for X. Always plural when referring to multiple consequences: "has implications".',
    domain: 'academic',
  },

  // ─── Sublist 6 ────────────────────────────────────────────────

  {
    id: 'awl_06_inherent',
    sublist: 6,
    headword: 'inherent',
    type: 'definition_match',
    options: [
      'developed through practice and experience',
      'existing as a natural or essential part of something',
      'obtained from an external source',
      'deliberately added to improve a situation',
    ],
    answer: 'existing as a natural or essential part of something',
    definition: 'existing as a natural or essential characteristic of something',
    explanation: '"Inherent risks" = risks that are a natural part of the activity, not introduced from outside. "Inherent in" is the common preposition: "risks inherent in the process".',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_06_nonetheless',
    sublist: 6,
    headword: 'nonetheless',
    type: 'gap_fill',
    sentence: 'The sample size was small; {{gap}}, the findings are consistent with previous research.',
    options: ['nonetheless', 'therefore', 'consequently', 'furthermore'],
    answer: 'nonetheless',
    definition: 'in spite of what has just been said; nevertheless',
    explanation: '"Nonetheless" = despite the limitation just mentioned, the findings are still valid. It introduces a contrasting point. "Therefore" and "consequently" introduce results, not contrasts.',
    domain: 'academic',
  },

  // ─── Sublist 7 ────────────────────────────────────────────────

  {
    id: 'awl_07_commence',
    sublist: 7,
    headword: 'commence',
    type: 'definition_match',
    options: [
      'to bring something to an end',
      'to begin or start',
      'to move forward rapidly',
      'to review and assess progress',
    ],
    answer: 'to begin or start',
    definition: 'to begin or start (formal)',
    explanation: '"Commence" = begin (formal register). "The trial will commence next month." More formal than "start" or "begin" — typical of IELTS Academic texts.',
    domain: 'academic',
    sentence: undefined,
  },
  {
    id: 'awl_07_sustain',
    sublist: 7,
    headword: 'sustain',
    type: 'word_form',
    sentence: 'Economic growth must be {{gap}} over the long term if living standards are to improve.',
    options: ['sustained', 'sustaining', 'sustainably', 'sustainable'],
    answer: 'sustained',
    definition: 'continuing for a long period without interruption',
    explanation: '"Must be sustained" = must be kept going continuously. Past participle after "be" for passive. "Sustainable" = able to be maintained, slightly different meaning.',
    domain: 'economics',
  },

  // ─── Sublist 8 ────────────────────────────────────────────────

  {
    id: 'awl_08_coherent',
    sublist: 8,
    headword: 'coherent',
    type: 'gap_fill',
    sentence: 'A {{gap}} argument is one in which each point flows logically from the previous one.',
    options: ['coherent', 'cohesive', 'cohesion', 'coherence'],
    answer: 'coherent',
    definition: 'logical and consistent; easy to understand',
    explanation: '"A coherent argument" — adjective before noun. "Coherent" = logically connected and clear. Distinguish from "cohesive" (= sticking together as a unit).',
    domain: 'academic',
  },
  {
    id: 'awl_08_paradigm',
    sublist: 8,
    headword: 'paradigm',
    type: 'definition_match',
    options: [
      'a set of rules governing academic writing',
      'a typical example or pattern; a conceptual framework within which theories operate',
      'the central argument of a research paper',
      'a statistical method for comparing data sets',
    ],
    answer: 'a typical example or pattern; a conceptual framework within which theories operate',
    definition: 'a typical example, pattern, or conceptual model that defines a field of thinking',
    explanation: '"A paradigm shift" = a fundamental change in the basic assumptions of a field. Very common in academic and IELTS texts: "Kuhn\'s concept of the scientific paradigm."',
    domain: 'academic',
    sentence: undefined,
  },

  // ─── Sublist 9 ────────────────────────────────────────────────

  {
    id: 'awl_09_aggregate',
    sublist: 9,
    headword: 'aggregate',
    type: 'gap_fill',
    sentence: 'In the {{gap}}, the reforms had little effect on overall inequality.',
    options: ['aggregate', 'aggregation', 'aggregated', 'aggregating'],
    answer: 'aggregate',
    definition: 'a total amount formed by adding together individual parts',
    explanation: '"In the aggregate" = taken as a whole, overall. "Aggregate" as a noun/adjective. Also: "aggregate demand/supply" in economics.',
    domain: 'economics',
  },
  {
    id: 'awl_09_empirical',
    sublist: 9,
    headword: 'empirical',
    type: 'definition_match',
    options: [
      'relating to theories that cannot be tested experimentally',
      'based on observation and experience rather than theory',
      'produced through mathematical calculation',
      'derived from expert opinion rather than data',
    ],
    answer: 'based on observation and experience rather than theory',
    definition: 'based on observation, experiment, and evidence rather than on theory alone',
    explanation: '"Empirical evidence" = evidence from real-world observation or experiments. Contrast with "theoretical" — IELTS Academic texts frequently distinguish these.',
    domain: 'academic',
    sentence: undefined,
  },

  // ─── Sublist 10 ───────────────────────────────────────────────

  {
    id: 'awl_10_comprises',
    sublist: 10,
    headword: 'comprise',
    type: 'gap_fill',
    sentence: 'The committee {{gap}} twelve members from across the country.',
    options: ['comprises', 'is comprised of', 'compose', 'consists'],
    answer: 'comprises',
    definition: 'to consist of or be made up of',
    explanation: '"Comprises" = consists of / is made up of. "The committee comprises twelve members" is the standard academic usage. "Is comprised of" is technically controversial but widely accepted.',
    domain: 'academic',
  },
  {
    id: 'awl_10_ubiquitous',
    sublist: 10,
    headword: 'ubiquitous',
    type: 'definition_match',
    options: [
      'found only in specialised or rare circumstances',
      'present, appearing, or found everywhere',
      'changing frequently and unpredictably',
      'relating to only one specific domain',
    ],
    answer: 'present, appearing, or found everywhere',
    definition: 'present, appearing, or found everywhere simultaneously',
    explanation: '"Smartphones have become ubiquitous." Means so common and widespread as to seem to be everywhere. C1-level vocabulary, AWL sublist 10.',
    domain: 'academic',
    sentence: undefined,
  },

]

export const AWL_SUBLIST_INFO: Record<AWLSublist, { description: string; frequency: string }> = {
  1:  { description: 'Most frequent academic words — essential for all IELTS tasks', frequency: '✦✦✦✦✦' },
  2:  { description: 'Very frequent — appear in most academic texts',                frequency: '✦✦✦✦✧' },
  3:  { description: 'Frequent — core academic vocabulary',                          frequency: '✦✦✦✦✧' },
  4:  { description: 'Common in academic writing across disciplines',                frequency: '✦✦✦✧✧' },
  5:  { description: 'Moderately frequent',                                          frequency: '✦✦✦✧✧' },
  6:  { description: 'Moderately frequent — appear in specialised texts',            frequency: '✦✦✧✧✧' },
  7:  { description: 'Less frequent but important for B2-C1',                        frequency: '✦✦✧✧✧' },
  8:  { description: 'Less frequent — advanced academic texts',                      frequency: '✦✧✧✧✧' },
  9:  { description: 'Relatively rare — specialised academic contexts',              frequency: '✦✧✧✧✧' },
  10: { description: 'Least frequent AWL words — advanced/C1 level',                frequency: '✦✧✧✧✧' },
}
