import type { CEFRLevel } from '@/types'

export interface IELTSWord {
  word: string
  definition: string
  example: string
  level: CEFRLevel
  partOfSpeech: string
}

export interface IELTSTopic {
  id: string
  title: string
  emoji: string
  description: string
  color: string
  words: IELTSWord[]
}

export const IELTS_TOPICS: IELTSTopic[] = [

  // ─── 1. Environment ───────────────────────────────────────────
  {
    id: 'environment',
    title: 'Environment',
    emoji: '🌿',
    description: 'Climate change, pollution, conservation, biodiversity — one of the most common IELTS topics.',
    color: '#16a34a',
    words: [
      { word: 'deforestation', definition: 'The large-scale removal of forests, often for agriculture or logging', example: 'Deforestation in the Amazon has accelerated at an alarming rate over the past decade.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'biodiversity', definition: 'The variety of plant and animal species in a particular habitat or on Earth', example: 'Protecting biodiversity is essential for maintaining the balance of ecosystems.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'carbon footprint', definition: 'The total greenhouse gas emissions caused by a person, product, or event', example: 'Many companies are trying to reduce their carbon footprint by switching to renewable energy.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'renewable energy', definition: 'Energy from sources that are naturally replenished, such as solar or wind', example: 'Investment in renewable energy has grown significantly over the last ten years.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'sustainable', definition: 'Able to be maintained without depleting natural resources or causing ecological damage', example: 'Sustainable farming practices help preserve soil quality for future generations.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'emissions', definition: 'Gases or substances released into the atmosphere, especially greenhouse gases', example: 'The government pledged to reduce carbon emissions by 50% before 2030.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'ecosystem', definition: 'A complex network of living organisms and their physical environment', example: 'The coral reef ecosystem is home to thousands of species of fish and marine life.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'conservation', definition: 'The careful management and protection of the environment and natural resources', example: 'Wildlife conservation efforts have helped several endangered species recover.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'contamination', definition: 'The presence of harmful substances in water, air, or soil', example: 'Industrial contamination of the river has devastated local fish populations.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'desertification', definition: 'The process by which fertile land becomes desert, typically through drought or deforestation', example: 'Desertification in sub-Saharan Africa is threatening the livelihoods of millions of people.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'habitat loss', definition: 'Destruction of natural environments where plants and animals live', example: 'Habitat loss due to urban expansion is the leading cause of species extinction.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'greenhouse effect', definition: 'The trapping of heat in the atmosphere by gases such as CO2, causing global warming', example: 'Human activities have intensified the greenhouse effect, leading to rising temperatures.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'mitigate', definition: 'To reduce the severity or seriousness of something, especially a problem', example: 'Planting urban trees can help mitigate the effects of air pollution in cities.', level: 'C1', partOfSpeech: 'verb' },
      { word: 'ecological', definition: 'Relating to the relationship between living organisms and their environment', example: 'The construction project will have serious ecological consequences for the wetlands.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'fossil fuels', definition: 'Fuels formed from ancient organic matter, including coal, oil, and natural gas', example: 'Burning fossil fuels releases carbon dioxide, contributing to climate change.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'endangered species', definition: 'Plants or animals at serious risk of extinction', example: 'The giant panda was once critically endangered but is now listed as vulnerable.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'pollutant', definition: 'A substance that contaminates the environment and causes harm', example: 'Car exhaust fumes are a major pollutant in densely populated urban areas.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'degrade', definition: 'To reduce something to a lower quality or state, especially land or the environment', example: 'Intensive agriculture can degrade soil quality, making it less productive over time.', level: 'C1', partOfSpeech: 'verb' },
      { word: 'climate change', definition: 'Long-term shifts in global temperatures and weather patterns, largely caused by human activity', example: 'Climate change is increasing the frequency of extreme weather events worldwide.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'carbon neutral', definition: 'Producing no net carbon emissions by balancing emissions with offsetting measures', example: 'The airline aims to become carbon neutral by investing in tree-planting programmes.', level: 'C1', partOfSpeech: 'adjective' },
    ],
  },

  // ─── 2. Technology ────────────────────────────────────────────
  {
    id: 'technology',
    title: 'Technology',
    emoji: '💻',
    description: 'AI, automation, digital society, privacy — heavily featured in IELTS Reading and Writing.',
    color: '#2563eb',
    words: [
      { word: 'artificial intelligence', definition: 'Computer systems that perform tasks typically requiring human intelligence', example: 'Artificial intelligence is transforming industries from healthcare to finance.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'automation', definition: 'The use of technology to perform tasks without human involvement', example: 'Automation has increased factory efficiency but reduced the need for manual labour.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'digital divide', definition: 'The gap between those who have access to digital technology and those who do not', example: 'The digital divide between developed and developing nations is widening.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'data privacy', definition: 'The right of individuals to control how their personal data is collected and used', example: 'Growing concerns about data privacy have led to stricter regulations in many countries.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'algorithm', definition: 'A set of rules or instructions followed by a computer to solve a problem', example: 'Social media algorithms determine which content appears in your feed.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'innovation', definition: 'The introduction of new ideas, products, or processes', example: 'Continuous innovation is essential for companies to remain competitive.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'surveillance', definition: 'Monitoring of individuals or groups, especially by governments or organisations', example: 'Critics argue that increased digital surveillance threatens individual freedoms.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'obsolete', definition: 'No longer in use or production because something newer has replaced it', example: 'Many traditional jobs have become obsolete as automation takes over.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'disruptive', definition: 'Causing major change to an industry or market through new ideas or technology', example: 'Ride-sharing apps have been disruptive to the traditional taxi industry.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'cybersecurity', definition: 'The practice of protecting systems, networks, and programmes from digital attacks', example: 'Cybersecurity threats have grown more sophisticated with advances in technology.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'virtual reality', definition: 'A simulated environment experienced through a computer headset', example: 'Virtual reality is increasingly used in medical training and education.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'renewable technology', definition: 'Technology that generates energy from natural, sustainable sources', example: 'Investment in renewable technology has made solar panels significantly cheaper.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'autonomous', definition: 'Self-governing or self-directing; in technology, able to operate without human control', example: 'Autonomous vehicles could significantly reduce road accidents caused by human error.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'misinformation', definition: 'False or inaccurate information, especially when spread on social media', example: 'The rapid spread of misinformation online poses a serious threat to public health.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'infrastructure', definition: 'The basic physical systems of a country or organisation, such as roads and networks', example: 'Digital infrastructure is as important as physical infrastructure in modern economies.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'bioengineering', definition: 'The application of engineering principles to biology, medicine, and living organisms', example: 'Bioengineering advances have made it possible to grow human tissue in laboratories.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'digitise', definition: 'To convert information or processes into digital format', example: 'Many governments are working to digitise public services to improve efficiency.', level: 'B2', partOfSpeech: 'verb' },
      { word: 'productivity', definition: 'The efficiency with which goods or services are produced', example: 'New software tools have greatly increased employee productivity in the workplace.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'dependency', definition: 'The state of relying heavily on something or someone', example: 'Society\'s growing dependency on smartphones raises concerns about mental health.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'genomics', definition: 'The study of genes and their functions, including the human genome', example: 'Advances in genomics have revolutionised the diagnosis and treatment of genetic disorders.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 3. Education ─────────────────────────────────────────────
  {
    id: 'education',
    title: 'Education',
    emoji: '🎓',
    description: 'Learning systems, university, online learning, skills — very common in IELTS Writing Task 2.',
    color: '#7c3aed',
    words: [
      { word: 'curriculum', definition: 'The subjects and content taught in a school or educational programme', example: 'There are growing calls to include financial literacy in the school curriculum.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'tuition', definition: 'Teaching or instruction, or the fee charged for education', example: 'Rising university tuition fees are discouraging students from lower-income backgrounds.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'literacy', definition: 'The ability to read and write; also used broadly for competence in a field', example: 'Digital literacy is now considered as important as traditional literacy skills.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'vocational', definition: 'Related to the skills and training needed for a specific job or career', example: 'Vocational courses are a practical alternative for students who prefer hands-on learning.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'academic achievement', definition: 'The level of success attained in educational studies', example: 'Academic achievement is not the only measure of a student\'s potential or worth.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'standardised testing', definition: 'Examinations that are administered and scored in a consistent manner across all test-takers', example: 'Critics argue that standardised testing fails to capture the full range of student abilities.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'extracurricular', definition: 'Outside the regular academic curriculum; additional school activities', example: 'Extracurricular activities such as sport and music help students develop well-rounded skills.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'pedagogy', definition: 'The theory and practice of teaching; methods of instruction', example: 'Modern pedagogy emphasises student-centred learning over rote memorisation.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'scholarship', definition: 'Financial support given to a student to help pay for their education', example: 'She received a full scholarship to study engineering at a prestigious university.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'graduate', definition: 'A person who has completed a university degree; also, to complete such a degree', example: 'Many graduates struggle to find employment that matches their level of qualification.', level: 'B1', partOfSpeech: 'noun/verb' },
      { word: 'critical thinking', definition: 'The ability to analyse information objectively and make reasoned judgements', example: 'Universities increasingly value critical thinking over the ability to memorise facts.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'inclusive education', definition: 'An approach that ensures all students, regardless of ability, can learn together', example: 'Inclusive education benefits both disabled and non-disabled students by building empathy.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'dropout rate', definition: 'The percentage of students who leave school or university before completing their course', example: 'High dropout rates in secondary school are linked to poverty and lack of family support.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'remote learning', definition: 'Education delivered outside a traditional classroom, typically online', example: 'Remote learning became essential during the pandemic but revealed a significant digital divide.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'competency', definition: 'The ability to do something successfully or efficiently', example: 'Employers increasingly look for competency in communication and problem-solving.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'peer learning', definition: 'Learning that occurs through interaction and collaboration with classmates', example: 'Peer learning can be highly effective as students often explain concepts in more accessible ways.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'lifelong learning', definition: 'The ongoing, self-motivated pursuit of knowledge throughout a person\'s life', example: 'In rapidly changing industries, a commitment to lifelong learning has become essential.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'rote learning', definition: 'Memorising information through repetition without necessarily understanding it', example: 'Critics of rote learning argue it produces students who can recite facts but not apply them.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'intellectual', definition: 'Relating to the mind; a person who engages deeply with ideas and learning', example: 'University should be a place that stimulates intellectual curiosity and debate.', level: 'B2', partOfSpeech: 'adjective/noun' },
      { word: 'disparity', definition: 'A great difference or inequality, especially in educational opportunity', example: 'The disparity in education quality between rural and urban areas remains a serious concern.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 4. Health ────────────────────────────────────────────────
  {
    id: 'health',
    title: 'Health',
    emoji: '🏥',
    description: 'Public health, mental health, healthcare systems, nutrition — regular IELTS topic.',
    color: '#dc2626',
    words: [
      { word: 'epidemic', definition: 'A widespread occurrence of an infectious disease in a community at a particular time', example: 'An epidemic of obesity in developed nations is straining healthcare systems.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sedentary lifestyle', definition: 'A way of living that involves little physical activity', example: 'A sedentary lifestyle is a major risk factor for heart disease and type 2 diabetes.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'preventive healthcare', definition: 'Measures taken to prevent disease rather than treat it after it occurs', example: 'Investing in preventive healthcare reduces long-term costs on the medical system.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'mental health', definition: 'A person\'s emotional, psychological, and social wellbeing', example: 'Mental health awareness has grown significantly over the past decade.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'chronic disease', definition: 'A long-lasting health condition that generally cannot be cured, only managed', example: 'Chronic diseases such as diabetes and heart disease account for the majority of healthcare costs.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'vaccination', definition: 'The administration of a vaccine to protect against disease', example: 'Mass vaccination programmes have eradicated or significantly reduced many deadly diseases.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'obesity', definition: 'A medical condition in which excess body fat has accumulated to a degree that may impair health', example: 'Obesity rates have tripled globally since 1975, creating a major public health crisis.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'healthcare system', definition: 'The organised provision of medical care within a country or region', example: 'Countries with universal healthcare systems tend to have better public health outcomes.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'malnutrition', definition: 'Lack of proper nutrition, caused by insufficient or unbalanced food intake', example: 'Malnutrition in early childhood can have lasting effects on cognitive development.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'wellbeing', definition: 'The state of being comfortable, healthy, and happy', example: 'Workplaces are increasingly recognising the importance of employee wellbeing.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'pandemic', definition: 'An epidemic that has spread across multiple countries or continents', example: 'The COVID-19 pandemic exposed significant weaknesses in global health systems.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'pharmaceutical', definition: 'Relating to medicinal drugs; a pharmaceutical company produces medicines', example: 'Pharmaceutical companies invest billions in research to develop new treatments.', level: 'C1', partOfSpeech: 'adjective/noun' },
      { word: 'mortality rate', definition: 'The number of deaths in a given population over a period of time', example: 'Improved sanitation has dramatically reduced infant mortality rates worldwide.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'stigma', definition: 'A mark of disgrace associated with a particular circumstance, quality, or person', example: 'The stigma surrounding mental health often prevents people from seeking help.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'diagnosis', definition: 'The identification of the nature of an illness or problem through examination', example: 'Early diagnosis of cancer significantly improves the chances of successful treatment.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'life expectancy', definition: 'The average period a person may expect to live', example: 'Life expectancy has increased globally due to advances in medicine and public sanitation.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'rehabilitation', definition: 'The process of restoring someone to health or normal life through therapy', example: 'Physical rehabilitation after surgery is essential for a full recovery.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'holistic', definition: 'Treating the whole person, including mental and social factors, not just physical symptoms', example: 'A holistic approach to health considers diet, exercise, and mental wellbeing together.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'access to healthcare', definition: 'The ability of individuals to obtain needed medical services', example: 'Unequal access to healthcare remains one of the most serious forms of social inequality.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'antibiotic resistance', definition: 'The ability of bacteria to survive and grow despite antibiotic treatment', example: 'Antibiotic resistance is one of the most urgent threats to global public health.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 5. Society ───────────────────────────────────────────────
  {
    id: 'society',
    title: 'Society',
    emoji: '👥',
    description: 'Inequality, community, social issues, demographics — very broad and common in Task 2.',
    color: '#d97706',
    words: [
      { word: 'inequality', definition: 'Unfair differences in wealth, opportunity, or treatment between groups of people', example: 'Growing income inequality is threatening social cohesion in many developed countries.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'demographic', definition: 'Relating to population structure; a particular sector of the population', example: 'An ageing demographic is placing greater pressure on pension and healthcare systems.', level: 'C1', partOfSpeech: 'adjective/noun' },
      { word: 'social mobility', definition: 'The ability of individuals or groups to move up or down the social ladder', example: 'Education is often seen as the primary driver of social mobility.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'urbanisation', definition: 'The process by which more people come to live in cities rather than rural areas', example: 'Rapid urbanisation in Asia has created both economic opportunities and housing crises.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'cohesion', definition: 'The quality of forming a united whole; social cohesion refers to bonds between people', example: 'Strong community cohesion is essential for maintaining trust in public institutions.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'marginalised', definition: 'Treated as insignificant or excluded from mainstream society', example: 'Marginalised communities often have the least access to quality education and healthcare.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'gender equality', definition: 'Equal rights and opportunities for people of all genders', example: 'Despite progress, gender equality in the workplace remains far from complete.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'discrimination', definition: 'Unjust or prejudicial treatment of people on the basis of their identity', example: 'Age discrimination in hiring practices prevents many experienced workers from finding jobs.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'poverty', definition: 'The state of being extremely poor; lacking basic necessities', example: 'Poverty remains the root cause of many social and health problems in developing countries.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'welfare state', definition: 'A system where the government provides social security and services for its citizens', example: 'The welfare state ensures that citizens receive support during unemployment and illness.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'assimilation', definition: 'The process of adopting the culture and customs of a new country or group', example: 'The degree to which immigrants assimilate depends heavily on social and economic conditions.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'multiculturalism', definition: 'The coexistence of multiple cultures within a single society', example: 'Multiculturalism enriches societies by introducing diverse perspectives, foods, and traditions.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'ageing population', definition: 'A trend where the median age of a population rises due to falling birth rates and longer lives', example: 'An ageing population places greater demands on social care and pension systems.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'consumerism', definition: 'The preoccupation with buying goods and the belief that this brings happiness', example: 'Critics of consumerism argue that it encourages waste and environmental destruction.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'homelessness', definition: 'The condition of not having a stable, safe, or adequate place to live', example: 'Rising property prices are driving increasing rates of homelessness in major cities.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'migration', definition: 'Movement of people from one place to another, especially to find work or safety', example: 'Economic migration has shaped the demographic composition of many Western nations.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'work-life balance', definition: 'The division of time between work commitments and personal activities', example: 'Flexible working hours can significantly improve employees\' work-life balance.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'social norms', definition: 'The unwritten rules of behaviour that are considered acceptable in a group or society', example: 'Social norms around gender roles have shifted significantly in recent decades.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'volunteer', definition: 'To freely offer to do something; a person who works without being paid', example: 'Volunteering in the community builds social connections and a sense of purpose.', level: 'B1', partOfSpeech: 'verb/noun' },
      { word: 'philanthropy', definition: 'The desire to promote the welfare of others, especially through charitable donation', example: 'Corporate philanthropy has funded hospitals, schools, and arts programmes worldwide.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 6. Economy ───────────────────────────────────────────────
  {
    id: 'economy',
    title: 'Economy',
    emoji: '📈',
    description: 'Globalisation, trade, employment, development — common in IELTS Reading and Task 2.',
    color: '#0891b2',
    words: [
      { word: 'globalisation', definition: 'The process by which economies and cultures become interconnected worldwide', example: 'Globalisation has enabled companies to source materials and sell products across the world.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'recession', definition: 'A period of temporary economic decline, defined as two consecutive quarters of GDP fall', example: 'The 2008 recession led to widespread unemployment and business closures.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'inflation', definition: 'A general increase in prices and fall in the purchasing power of money', example: 'High inflation erodes savings and reduces the standard of living for fixed-income earners.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'GDP (gross domestic product)', definition: 'The total value of goods and services produced in a country over a specific period', example: 'A country\'s GDP is commonly used as a measure of economic health and development.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'unemployment', definition: 'The condition of being unable to find work, or the rate at which this occurs', example: 'Youth unemployment remains stubbornly high in many European economies.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'free trade', definition: 'International trade without government restrictions such as tariffs or quotas', example: 'Proponents of free trade argue it lowers prices and promotes economic growth.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'outsourcing', definition: 'Arranging for another company to do work that was previously done internally', example: 'Many firms have cut costs by outsourcing manufacturing to lower-wage countries.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'austerity', definition: 'Strict economic policies that reduce spending to decrease a government\'s deficit', example: 'Austerity measures introduced after the financial crisis led to significant cuts in public services.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'subsidy', definition: 'A sum of money granted by the government to support an industry or activity', example: 'Agricultural subsidies help protect farmers from market volatility.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'entrepreneurship', definition: 'The activity of setting up and running a business, taking financial risks', example: 'A culture of entrepreneurship is essential for innovation and economic growth.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'income gap', definition: 'The difference in earnings between the wealthiest and poorest members of society', example: 'The income gap between the richest 1% and the rest of society has widened sharply.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'fiscal policy', definition: 'Government decisions about spending and taxation to influence the economy', example: 'Expansionary fiscal policy, such as increased government spending, can stimulate growth.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'trade deficit', definition: 'The amount by which a country\'s imports exceed its exports', example: 'A persistent trade deficit can weaken a country\'s currency over time.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'economic development', definition: 'The process of improving the economic, social, and institutional environment of a country', example: 'Microfinance programmes have contributed to economic development in rural communities.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sustainability', definition: 'The ability to be maintained or continued over the long term without causing harm', example: 'Economic sustainability requires balancing growth with environmental protection.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'monopoly', definition: 'Exclusive control of the supply of a commodity or service by one company', example: 'Regulators are concerned that the merger would create a monopoly in the telecoms sector.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'living standards', definition: 'The degree of wealth and material comfort available to a person or group', example: 'Rising living standards in Asia have transformed global consumer markets.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'debt', definition: 'Money owed by one party to another, whether personal, corporate, or national', example: 'Many developing countries struggle under the burden of significant national debt.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'investment', definition: 'The act of putting money into something with the expectation of a return', example: 'Foreign direct investment has driven rapid industrialisation in many Asian economies.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'privatisation', definition: 'The transfer of public services or industries from government to private ownership', example: 'The privatisation of rail services has been controversial in many countries.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 7. Government & Politics ─────────────────────────────────
  {
    id: 'government',
    title: 'Government & Politics',
    emoji: '🏛️',
    description: 'Policy, democracy, rights, governance — frequently tested in IELTS Writing Task 2.',
    color: '#475569',
    words: [
      { word: 'democracy', definition: 'A system of government in which power is held by the people, typically through elections', example: 'Freedom of the press is a fundamental pillar of a functioning democracy.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'legislation', definition: 'Laws considered collectively; the process of making laws', example: 'New legislation has been introduced to tackle online hate speech.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'policy', definition: 'A course of action adopted by a government or organisation', example: 'Environmental policy has become a central issue in many national elections.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'governance', definition: 'The way in which a country or organisation is managed and the systems for doing this', example: 'Good governance is essential for sustainable economic development.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'taxation', definition: 'The system of collecting money from people to fund public services', example: 'Progressive taxation requires higher earners to contribute a larger share.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'corruption', definition: 'Dishonest or fraudulent conduct by those in power, typically involving bribery', example: 'Corruption undermines public trust in institutions and deters foreign investment.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'human rights', definition: 'Basic rights and freedoms to which all humans are entitled', example: 'Freedom of expression and the right to education are fundamental human rights.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'civil liberties', definition: 'Freedoms guaranteed to individuals by law, limiting government interference', example: 'Mass surveillance raises serious questions about civil liberties and privacy.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'bureaucracy', definition: 'A system of government with many complicated rules and processes', example: 'Excessive bureaucracy can slow down business operations and deter investment.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'referendum', definition: 'A direct vote by the people on a specific political question', example: 'The country held a referendum on whether to leave the trading bloc.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sanctions', definition: 'Penalties imposed by one country on another to force a change in behaviour', example: 'Economic sanctions have been imposed on the country in response to human rights abuses.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'lobbying', definition: 'Seeking to influence politicians or officials on a particular issue', example: 'Corporate lobbying has been criticised for giving wealthy interests too much political influence.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'censorship', definition: 'The suppression or prohibition of speech, writing, or other communication', example: 'Internet censorship restricts the flow of information and limits free expression.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'infrastructure investment', definition: 'Government spending on physical systems like roads, bridges, and utilities', example: 'Infrastructure investment can boost productivity and create long-term economic growth.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'accountability', definition: 'The fact of being responsible for one\'s actions and having to explain them', example: 'Public accountability is essential to prevent misuse of government funds.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'authoritarian', definition: 'Favouring or enforcing strict obedience to authority, especially in government', example: 'Authoritarian regimes typically restrict freedom of speech and political opposition.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'treaty', definition: 'A formal agreement between countries', example: 'The two countries signed a trade treaty to reduce tariffs and promote commerce.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'social welfare', definition: 'Government programmes designed to ensure basic standards of living for citizens', example: 'Social welfare spending accounts for a significant portion of most developed nations\' budgets.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'transparency', definition: 'Operating in an open way without secrets, especially in government and business', example: 'Transparency in government decision-making is essential for maintaining public trust.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sovereignty', definition: 'Supreme authority or power, especially of a state over its own affairs', example: 'National sovereignty is a central concept in international law and diplomacy.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 8. Media & Communication ────────────────────────────────
  {
    id: 'media',
    title: 'Media & Communication',
    emoji: '📱',
    description: 'Social media, journalism, advertising, influence — growing IELTS topic.',
    color: '#db2777',
    words: [
      { word: 'social media', definition: 'Websites and apps that enable people to create and share content or interact', example: 'Social media has transformed how political campaigns reach and mobilise voters.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'broadcasting', definition: 'Transmitting programmes by radio or television to a large audience', example: 'Public broadcasting provides a balanced alternative to commercially driven media.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'propaganda', definition: 'Information, especially biased or misleading, used to promote a political cause', example: 'State propaganda was used to control public opinion during the conflict.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'fake news', definition: 'False or deliberately misleading information presented as news', example: 'The proliferation of fake news has made it increasingly difficult to trust online sources.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'censorship', definition: 'The suppression of speech or media by an authority', example: 'Media censorship prevents journalists from reporting on government corruption.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'freedom of the press', definition: 'The right to publish news and opinions without government interference', example: 'Freedom of the press is considered a cornerstone of democratic society.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'advertising', definition: 'The activity of producing and distributing messages to promote products or services', example: 'Advertising targeted at children raises important ethical questions.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'clickbait', definition: 'Online content designed to attract clicks through sensational or misleading headlines', example: 'Many news websites rely on clickbait headlines to generate traffic and advertising revenue.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'viral', definition: 'Spreading rapidly and widely through social media or the internet', example: 'A video of the event went viral, reaching millions of viewers within hours.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'echo chamber', definition: 'An environment where a person encounters only beliefs that reinforce their own', example: 'Social media algorithms create echo chambers that reinforce existing biases.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'influencer', definition: 'A person with a large social media following who can affect others\' opinions', example: 'Brands pay influencers to promote their products to younger audiences.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'digital literacy', definition: 'The ability to use digital technology and evaluate online information critically', example: 'Digital literacy is now a core skill that schools must teach students.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'mainstream media', definition: 'The traditional major media outlets such as TV, radio, and newspapers', example: 'Trust in mainstream media has declined as people turn to alternative online sources.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'bias', definition: 'An inclination towards a particular perspective, unfairly favouring some over others', example: 'Media bias can significantly influence public perception of political issues.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'subscription model', definition: 'A business model where users pay regularly to access content or services', example: 'Many news organisations have shifted to a subscription model to ensure sustainable revenue.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'disinformation', definition: 'Deliberately false information spread to deceive people', example: 'Disinformation campaigns have undermined public confidence in vaccination programmes.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'print media', definition: 'Newspapers, magazines, and other publications on paper', example: 'Print media circulation has declined sharply as readers move online.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'accountability', definition: 'The obligation to accept responsibility for one\'s actions', example: 'Greater accountability from social media platforms is needed to tackle harmful content.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'podcast', definition: 'A digital audio programme available for streaming or download', example: 'Podcasts have emerged as a major format for news, education, and entertainment.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'content moderation', definition: 'The practice of reviewing and removing content on platforms that violates guidelines', example: 'Content moderation at scale remains one of the biggest challenges for social media companies.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 9. Crime & Justice ───────────────────────────────────────
  {
    id: 'crime',
    title: 'Crime & Justice',
    emoji: '⚖️',
    description: 'Punishment, rehabilitation, crime prevention — often appears in IELTS Writing Task 2.',
    color: '#374151',
    words: [
      { word: 'rehabilitation', definition: 'Helping offenders to return to normal life and become productive members of society', example: 'Prison rehabilitation programmes have been shown to reduce reoffending rates significantly.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'deterrent', definition: 'Something that discourages someone from taking a particular action', example: 'Harsher sentencing is often proposed as a deterrent to serious crime.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'recidivism', definition: 'The tendency to relapse into criminal behaviour after previous convictions', example: 'High recidivism rates suggest that imprisonment alone does not address the root causes of crime.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'capital punishment', definition: 'The legally authorised execution of someone as punishment for a crime', example: 'Capital punishment remains legal in a small number of countries despite widespread opposition.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'cybercrime', definition: 'Criminal activity carried out using computers or the internet', example: 'Cybercrime costs the global economy trillions of dollars annually.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'incarceration', definition: 'The state of being imprisoned', example: 'The United States has the highest incarceration rate of any developed nation.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'juvenile delinquency', definition: 'Criminal behaviour by young people under the age of majority', example: 'Poverty and lack of education are major contributing factors to juvenile delinquency.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'white-collar crime', definition: 'Non-violent crime committed by businesspeople, typically involving financial fraud', example: 'White-collar crime costs more than street crime but is often punished less severely.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'criminal justice system', definition: 'The institutions responsible for enforcing criminal law, including police, courts, and prisons', example: 'Reform of the criminal justice system is needed to address racial disparities in sentencing.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'corruption', definition: 'Dishonest conduct, typically involving bribery, by people in power', example: 'Police corruption undermines public trust in law enforcement.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'prevention', definition: 'Action taken to stop something from happening', example: 'Crime prevention programmes targeting at-risk youth have proven more cost-effective than imprisonment.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'sentence', definition: 'The punishment given to someone convicted of a crime by a court', example: 'The judge imposed a five-year sentence for the fraud offence.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'organised crime', definition: 'Criminal activity by a group of people working together in a planned way', example: 'Organised crime networks are involved in drug trafficking across multiple continents.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'forensic', definition: 'Relating to the use of scientific methods in investigating crimes', example: 'Forensic evidence played a crucial role in securing the conviction.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'domestic violence', definition: 'Violent or abusive behaviour within the home, typically by an intimate partner', example: 'Domestic violence cases increased significantly during pandemic lockdowns.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'trafficking', definition: 'Dealing in illegal goods or people, especially across borders', example: 'Human trafficking is one of the most serious violations of human rights.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'acquit', definition: 'To formally declare that someone is not guilty of a crime', example: 'The defendant was acquitted of all charges due to insufficient evidence.', level: 'C1', partOfSpeech: 'verb' },
      { word: 'parole', definition: 'The early release of a prisoner, subject to conditions of good behaviour', example: 'He was released on parole after serving half of his eight-year sentence.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'witness', definition: 'A person who sees or hears something; one who gives evidence in court', example: 'Witness protection programmes encourage people to testify against organised crime.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'lawsuit', definition: 'A legal dispute brought to a court of law for settlement', example: 'The company faces a major lawsuit over claims that its products caused health damage.', level: 'B2', partOfSpeech: 'noun' },
    ],
  },

  // ─── 10. Arts & Culture ───────────────────────────────────────
  {
    id: 'arts',
    title: 'Arts & Culture',
    emoji: '🎨',
    description: 'Heritage, creative industries, cultural preservation — less common but tested.',
    color: '#9333ea',
    words: [
      { word: 'cultural heritage', definition: 'The legacy of physical and intangible attributes inherited from past generations', example: 'Preserving cultural heritage is essential for maintaining a nation\'s identity and history.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'contemporary', definition: 'Belonging to or occurring in the present time; modern', example: 'Contemporary art often challenges conventional ideas about beauty and meaning.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'subsidise', definition: 'To pay part of the cost of something to make it affordable or viable', example: 'Governments often subsidise the arts because they generate cultural and economic value.', level: 'B2', partOfSpeech: 'verb' },
      { word: 'aesthetic', definition: 'Relating to beauty and the appreciation of art; a particular style or taste', example: 'The building\'s striking aesthetic has made it a landmark in the city.', level: 'C1', partOfSpeech: 'adjective/noun' },
      { word: 'indigenous', definition: 'Originating or occurring naturally in a particular place; relating to original inhabitants', example: 'Indigenous art forms are being revived to preserve cultural traditions.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'creativity', definition: 'The use of imagination or original ideas to produce something', example: 'Creativity is increasingly valued in the modern workplace as automation replaces routine tasks.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'patronage', definition: 'Financial support given to artists, musicians, or writers; also business given to a shop', example: 'Without government patronage, many orchestras and theatres would struggle to survive.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'narrative', definition: 'A spoken or written account of events; a story', example: 'Film has the power to challenge dominant narratives and shift public opinion.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'censorship', definition: 'The suppression of artistic or other expression by authorities', example: 'Artistic censorship prevents writers and artists from addressing controversial social issues.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'performing arts', definition: 'Art forms that are performed in front of an audience, such as theatre, dance, and music', example: 'Funding for performing arts has been cut significantly in many public budgets.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'gentrification', definition: 'The process of wealthy people moving into a poor urban area, raising property values', example: 'Gentrification often displaces artistic communities from the neighbourhoods they helped transform.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'preservation', definition: 'The maintenance and protection of something, especially historical or cultural artefacts', example: 'Digital preservation allows rare manuscripts and artworks to be accessed globally.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'globalisation of culture', definition: 'The spread of cultural products, ideas, and values across the world', example: 'The globalisation of culture raises fears about the loss of local traditions and languages.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'intangible', definition: 'Unable to be touched or physically defined; non-material', example: 'Language, music, and dance are intangible forms of cultural heritage.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'genre', definition: 'A category of artistic composition with similar content, style, or form', example: 'The crime fiction genre has produced some of the most widely read novels of the past century.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'exhibition', definition: 'A public display of art, products, or other items', example: 'The gallery\'s special exhibition attracted over 200,000 visitors in three months.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'heritage site', definition: 'A place recognised as having outstanding value to humanity, often by UNESCO', example: 'UNESCO World Heritage Sites attract millions of cultural tourists each year.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'cultural exchange', definition: 'The sharing of ideas, traditions, and practices between different cultures', example: 'Student exchange programmes promote cultural exchange and international understanding.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'homogenisation', definition: 'The process of making things uniform, often at the expense of diversity', example: 'Many critics fear that globalisation is leading to the homogenisation of world culture.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'avant-garde', definition: 'New and innovative, especially in arts; ahead of its time', example: 'The film was praised by critics for its avant-garde approach to storytelling.', level: 'C1', partOfSpeech: 'adjective' },
    ],
  },

  // ─── 11. Transport ────────────────────────────────────────────
  {
    id: 'transport',
    title: 'Transport',
    emoji: '🚆',
    description: 'Infrastructure, congestion, electric vehicles — common in IELTS Task 1 and 2.',
    color: '#059669',
    words: [
      { word: 'congestion', definition: 'Overcrowding on roads or in cities, causing traffic to slow or stop', example: 'Traffic congestion in major cities costs the economy billions in lost productivity each year.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'infrastructure', definition: 'The basic physical systems needed for transport, such as roads, rails, and bridges', example: 'Investing in transport infrastructure creates jobs and stimulates long-term economic growth.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'public transport', definition: 'Transport services available to the public, such as buses, trains, and subways', example: 'Improving public transport is one of the most effective ways to reduce urban emissions.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'electric vehicle (EV)', definition: 'A vehicle powered by electricity rather than petrol or diesel', example: 'The government is offering subsidies to encourage the purchase of electric vehicles.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'commute', definition: 'To travel regularly between home and work; the journey itself', example: 'Remote working has reduced the daily commute for millions of office workers.', level: 'B2', partOfSpeech: 'verb/noun' },
      { word: 'carbon emissions', definition: 'CO2 and other greenhouse gases released into the atmosphere by vehicles', example: 'Reducing carbon emissions from transport is central to achieving climate targets.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'pedestrian', definition: 'A person travelling on foot; relating to walking', example: 'City planners are creating more pedestrian zones to improve air quality and safety.', level: 'B1', partOfSpeech: 'noun/adjective' },
      { word: 'aviation', definition: 'The operation of aircraft; the aircraft industry', example: 'Aviation accounts for approximately 2.5% of global CO2 emissions.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'urban sprawl', definition: 'The uncontrolled spread of urban development into rural areas', example: 'Urban sprawl increases car dependency and makes public transport less viable.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'autonomous vehicle', definition: 'A self-driving car that does not require human control', example: 'Autonomous vehicles could eliminate most accidents caused by human error.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'toll', definition: 'A charge paid to use a road, bridge, or tunnel', example: 'Road tolls are used to fund infrastructure maintenance and discourage unnecessary journeys.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'cycling infrastructure', definition: 'Physical structures and facilities that support cycling, such as bike lanes', example: 'Cities with good cycling infrastructure have lower rates of obesity and air pollution.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'high-speed rail', definition: 'A railway system designed for significantly faster trains than conventional rail', example: 'High-speed rail can be a greener alternative to short-haul flights.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'gridlock', definition: 'A traffic jam affecting a whole network of streets; a complete standstill', example: 'The city centre frequently experiences gridlock during morning rush hour.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'subsidise', definition: 'To provide financial support to keep prices low or services viable', example: 'Many argue that governments should subsidise public transport to reduce car use.', level: 'B2', partOfSpeech: 'verb' },
      { word: 'freight', definition: 'Goods transported by road, rail, air, or sea', example: 'A significant portion of global freight still travels by container ship.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'road safety', definition: 'Measures and practices designed to prevent accidents and injuries on roads', example: 'Improved road safety campaigns have contributed to falling fatality rates.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'sustainable transport', definition: 'Transport that meets current needs without compromising future generations', example: 'Walking, cycling, and electric public transport are examples of sustainable transport.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'accessibility', definition: 'The quality of being easily reached or used, especially for people with disabilities', example: 'Improving accessibility on public transport is essential for an inclusive society.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'congestion charge', definition: 'A fee charged for driving in a busy urban area to reduce traffic', example: 'London\'s congestion charge has reduced traffic in the city centre by approximately 30%.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 12. Science & Research ───────────────────────────────────
  {
    id: 'science',
    title: 'Science & Research',
    emoji: '🔬',
    description: 'Scientific method, medical research, innovation — appears in IELTS Reading and Task 2.',
    color: '#0891b2',
    words: [
      { word: 'hypothesis', definition: 'A proposed explanation for a phenomenon, made as a starting point for investigation', example: 'The scientists formulated a hypothesis that diet affects cognitive performance.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'peer review', definition: 'The evaluation of scientific work by other experts in the same field', example: 'Peer review helps ensure the quality and accuracy of published research.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'ethics', definition: 'Moral principles governing a person\'s or group\'s conduct, especially in research', example: 'Research ethics committees ensure that human and animal subjects are treated appropriately.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'clinical trial', definition: 'A research study testing the safety and effectiveness of a medical treatment', example: 'The new drug must complete three phases of clinical trials before it can be approved.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'genome', definition: 'The complete set of genetic material present in an organism', example: 'Mapping the human genome has opened new possibilities for personalised medicine.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'empirical', definition: 'Based on observation and experiment rather than theory or logic alone', example: 'Empirical evidence from large-scale studies is more reliable than anecdotal reports.', level: 'C1', partOfSpeech: 'adjective' },
      { word: 'nanotechnology', definition: 'Technology involving the manipulation of matter at an atomic or molecular scale', example: 'Nanotechnology has potential applications in medicine, computing, and manufacturing.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'stem cell', definition: 'An undifferentiated cell capable of developing into specialised cell types', example: 'Stem cell research offers hope for the treatment of conditions like Parkinson\'s disease.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'findings', definition: 'The results or conclusions of a study or investigation', example: 'The research findings suggest a strong link between air quality and cognitive decline.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'breakthrough', definition: 'A significant discovery or development that removes a barrier or advances a field', example: 'The development of mRNA vaccines represented a major breakthrough in immunology.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'replication', definition: 'The repeating of a scientific experiment to verify its results', example: 'Many psychology studies have failed replication, raising questions about their validity.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'methodology', definition: 'A system of methods used in a particular area of study or activity', example: 'The study\'s methodology has been criticised for its small and unrepresentative sample size.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'biodegradable', definition: 'Capable of being decomposed by bacteria or other living organisms', example: 'Replacing plastic packaging with biodegradable materials could significantly reduce pollution.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'neuroscience', definition: 'The scientific study of the structure and function of the brain and nervous system', example: 'Neuroscience has revealed how early childhood experiences shape brain development.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'renewable resources', definition: 'Natural resources that can be replenished naturally over time', example: 'Shifting to renewable resources is essential for long-term environmental sustainability.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'experiment', definition: 'A scientific test conducted to discover something or prove a theory', example: 'A controlled experiment eliminates other variables to test a single hypothesis.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'correlation', definition: 'A relationship or connection between two variables', example: 'There is a strong correlation between levels of education and income.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'placebo', definition: 'A harmless treatment given as if it were medicine, used in clinical trials as a control', example: 'Participants receiving the placebo showed a 20% improvement, suggesting a strong placebo effect.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'innovation', definition: 'The introduction of new methods, ideas, or products', example: 'Scientific innovation requires significant investment and a culture of intellectual freedom.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'space exploration', definition: 'The investigation of space using technology such as spacecraft and telescopes', example: 'Space exploration has delivered numerous technological benefits to everyday life.', level: 'B1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 13. Food & Nutrition ─────────────────────────────────────
  {
    id: 'food',
    title: 'Food & Nutrition',
    emoji: '🍎',
    description: 'Diet, food security, agriculture, obesity — growing IELTS topic.',
    color: '#d97706',
    words: [
      { word: 'food security', definition: 'The state of having reliable access to a sufficient quantity of affordable, nutritious food', example: 'Climate change poses a significant threat to global food security.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'malnutrition', definition: 'Lack of proper nutrition, from insufficient or unbalanced food intake', example: 'Malnutrition remains a serious problem despite global food surpluses.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'organic', definition: 'Produced without artificial chemicals or genetic modification', example: 'Demand for organic produce has grown as consumers become more health-conscious.', level: 'B1', partOfSpeech: 'adjective' },
      { word: 'processed food', definition: 'Food that has been changed from its natural state through preservation, cooking, or additives', example: 'Excessive consumption of processed food is linked to obesity and chronic disease.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'dietary guidelines', definition: 'Official recommendations about what people should eat for good health', example: 'Government dietary guidelines recommend eating at least five portions of fruit and vegetables daily.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'food waste', definition: 'Food that is thrown away rather than consumed', example: 'About one-third of all food produced globally is wasted each year.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'agriculture', definition: 'The science and practice of farming, including growing crops and raising livestock', example: 'Sustainable agriculture can feed the world without destroying the environment.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'GMO (genetically modified organism)', definition: 'An organism whose genetic material has been altered using biotechnology', example: 'The debate over GMO crops involves both scientific and ethical considerations.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'calorie', definition: 'A unit of energy, used to measure the energy value of food', example: 'Calorie labelling on menus helps consumers make informed choices about what they eat.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'food industry', definition: 'The companies and businesses involved in producing, processing, and distributing food', example: 'The food industry spends billions on advertising, particularly targeting children.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'vegan', definition: 'Avoiding all animal products including meat, dairy, and eggs', example: 'A plant-based, vegan diet has a significantly lower carbon footprint than a meat-based diet.', level: 'B1', partOfSpeech: 'adjective/noun' },
      { word: 'food labelling', definition: 'The information provided on food packaging about ingredients, nutrition, and allergens', example: 'Clear food labelling enables consumers to compare the nutritional value of products.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'irrigation', definition: 'The supply of water to land for farming', example: 'Inefficient irrigation practices waste enormous amounts of water in arid regions.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'pesticide', definition: 'A chemical substance used to destroy insects or other organisms that damage crops', example: 'Pesticide use in agriculture has increased crop yields but raised environmental concerns.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'supply chain', definition: 'The sequence of processes involved in the production and distribution of a product', example: 'The global food supply chain is highly vulnerable to climate shocks and geopolitical events.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'saturated fat', definition: 'A type of fat found mainly in animal products, linked to heart disease in excess', example: 'Health authorities recommend limiting saturated fat intake to reduce the risk of cardiovascular disease.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'food poverty', definition: 'The inability to access adequate, nutritious food due to financial constraints', example: 'Food poverty has increased as a result of rising costs of living.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'urban farming', definition: 'Growing food in cities, often on rooftops, balconies, or in community gardens', example: 'Urban farming can contribute to food security and reduce the environmental cost of transport.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'subsistence farming', definition: 'Farming that produces only enough food for the farmer\'s own use', example: 'Millions of families in developing countries depend on subsistence farming for survival.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'plant-based diet', definition: 'A diet consisting mostly or entirely of plant foods, with little or no animal products', example: 'A plant-based diet can reduce environmental impact and improve health outcomes.', level: 'B2', partOfSpeech: 'noun' },
    ],
  },

  // ─── 14. Cities & Urban Life ──────────────────────────────────
  {
    id: 'cities',
    title: 'Cities & Urban Life',
    emoji: '🏙️',
    description: 'Urbanisation, housing, public spaces, smart cities — common in IELTS Task 1 and 2.',
    color: '#6366f1',
    words: [
      { word: 'urbanisation', definition: 'The process by which a greater portion of a population comes to live in cities', example: 'Rapid urbanisation in developing countries is creating both opportunities and social challenges.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'affordable housing', definition: 'Housing priced within the financial means of low- to moderate-income residents', example: 'The lack of affordable housing is forcing many workers to live far from their places of work.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'smart city', definition: 'An urban area that uses technology to improve infrastructure and services', example: 'Smart city initiatives use data to optimise traffic flow, waste management, and energy use.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'gentrification', definition: 'The renovation of deteriorated urban areas, often displacing lower-income residents', example: 'Gentrification has made city centres less accessible to the communities that once lived there.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'green space', definition: 'Land in or near a city that is covered with grass, trees, or other vegetation', example: 'Access to green space in urban areas improves mental health and community wellbeing.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'overpopulation', definition: 'When a population exceeds the capacity of the environment or infrastructure to support it', example: 'Urban overpopulation leads to strains on water, transport, and sanitation systems.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'urban planning', definition: 'The design and regulation of urban spaces, including housing, transport, and land use', example: 'Effective urban planning can reduce inequality by ensuring public services are distributed fairly.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'infrastructure', definition: 'Basic physical systems including transport, water supply, and buildings', example: 'Ageing infrastructure in many cities requires urgent investment to prevent failure.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'suburb', definition: 'A residential area on the outskirts of a city', example: 'Many families moved to the suburbs seeking more space and better schools.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'slum', definition: 'A densely populated urban area with poor living conditions', example: 'Over a billion people worldwide live in urban slums without access to basic services.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sanitation', definition: 'Conditions relating to public health, especially access to clean water and sewage disposal', example: 'Inadequate sanitation in densely populated cities contributes to the spread of disease.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'mixed-use development', definition: 'Urban development combining residential, commercial, and recreational uses in one area', example: 'Mixed-use development creates vibrant neighbourhoods where people can live, work, and socialise.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'noise pollution', definition: 'Harmful or disturbing noise in an urban environment', example: 'Noise pollution from traffic and construction is a major quality-of-life issue in cities.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'pedestrianisation', definition: 'Converting streets to pedestrian-only areas by excluding vehicles', example: 'Pedestrianisation of city centres has boosted retail trade and reduced air pollution.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'social segregation', definition: 'The separation of different groups within society, often based on class, race, or income', example: 'Social segregation in cities is reinforced when wealthy and poor communities have no shared spaces.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'community', definition: 'A group of people living in the same place, sharing common characteristics or interests', example: 'Strong communities with shared public spaces foster greater social cohesion.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'revitalisation', definition: 'The process of bringing new life or energy to a declining area', example: 'The waterfront revitalisation project has transformed a former industrial area into a thriving district.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'housing shortage', definition: 'A situation in which the supply of housing is insufficient to meet demand', example: 'The housing shortage in major cities has been driven by population growth and underinvestment.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'air quality', definition: 'The condition of the air in a given environment, especially in relation to pollution', example: 'Air quality in many Asian megacities regularly exceeds safe levels set by the WHO.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'urban heat island', definition: 'An urban area that is significantly warmer than surrounding rural areas due to human activity', example: 'Urban heat islands are intensifying heatwaves, posing serious health risks to city residents.', level: 'C1', partOfSpeech: 'noun' },
    ],
  },

  // ─── 15. Sports & Leisure ─────────────────────────────────────
  {
    id: 'sports',
    title: 'Sports & Leisure',
    emoji: '⚽',
    description: 'Physical activity, professional sport, recreation — occasionally tested in IELTS.',
    color: '#059669',
    words: [
      { word: 'physical activity', definition: 'Any movement of the body that requires energy expenditure', example: 'Regular physical activity reduces the risk of heart disease, diabetes, and depression.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'elite athlete', definition: 'A sportsperson who performs at the highest competitive level', example: 'Elite athletes often train for six to eight hours a day under intense pressure.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'doping', definition: 'The use of banned substances or methods to enhance athletic performance', example: 'Doping scandals have damaged the credibility of several major international sporting events.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'commercialisation', definition: 'The process of managing or running something in a way primarily concerned with making profit', example: 'The commercialisation of football has made it inaccessible to many working-class fans.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'sedentary', definition: 'Characterised by much sitting and little physical exercise', example: 'A sedentary lifestyle among young people is contributing to rising rates of obesity.', level: 'B2', partOfSpeech: 'adjective' },
      { word: 'spectator', definition: 'A person who watches an event or activity', example: 'The stadium can accommodate 80,000 spectators for major international matches.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'Olympic Games', definition: 'The world\'s foremost international sporting event, held every four years', example: 'Hosting the Olympic Games can boost tourism and infrastructure but at enormous cost.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'recreation', definition: 'Activity done for enjoyment when not working', example: 'Access to recreational facilities is linked to improved mental health in communities.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'gender pay gap in sport', definition: 'The difference in earnings between male and female professional athletes', example: 'The gender pay gap in sport remains significant despite growing audiences for women\'s events.', level: 'C1', partOfSpeech: 'noun' },
      { word: 'endurance', definition: 'The ability to sustain prolonged physical or mental effort', example: 'Marathon running requires exceptional endurance and mental resilience.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'participation rate', definition: 'The percentage of a population who actively engage in a sport or activity', example: 'Participation rates in team sports decline sharply after people leave school.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'sponsorship', definition: 'Financial support given to a person or event in return for advertising rights', example: 'Corporate sponsorship has transformed professional sport into a multi-billion dollar industry.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'wellbeing', definition: 'The state of being comfortable, healthy, and happy', example: 'Regular exercise contributes significantly to both physical and mental wellbeing.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'accessibility', definition: 'The quality of being easy to obtain or use, especially for those with disabilities', example: 'Improving accessibility at sports venues ensures that disabled fans can attend events.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'professional athlete', definition: 'A person who earns a living primarily from competing in sport', example: 'Only a tiny fraction of young people who play sport go on to become professional athletes.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'obesity epidemic', definition: 'A widespread increase in rates of obesity in a population', example: 'Tackling the obesity epidemic requires both increased physical activity and dietary changes.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'team spirit', definition: 'Feelings of camaraderie and motivation shared by members of a group', example: 'Sport builds team spirit and teaches collaboration, qualities valued in the workplace.', level: 'B1', partOfSpeech: 'noun' },
      { word: 'national identity', definition: 'The sense of belonging to a particular nation, often expressed through cultural symbols', example: 'International sporting success can strengthen national identity and social cohesion.', level: 'B2', partOfSpeech: 'noun' },
      { word: 'competitive', definition: 'Having a strong desire to win or be the best at something', example: 'A competitive environment in sport can motivate athletes to achieve their best performance.', level: 'B1', partOfSpeech: 'adjective' },
      { word: 'disability sport', definition: 'Sports designed for or involving athletes with physical or cognitive disabilities', example: 'The Paralympic Games have raised awareness and respect for disability sport globally.', level: 'B2', partOfSpeech: 'noun' },
    ],
  },

]
