import type { CEFRLevel } from '@/types'

export type TransformCategory =
  | 'passive'
  | 'reported_speech'
  | 'conditionals'
  | 'comparatives'
  | 'causative'
  | 'modal_verbs'
  | 'relative_clauses'
  | 'inversion'
  | 'gerund_infinitive'
  | 'phrasal_verbs'

export interface SentenceTransformation {
  id: string
  level: CEFRLevel
  category: TransformCategory
  original: string
  keyword: string
  // answer is the MIDDLE part only (between the fixed beginnings/ends shown to user)
  // fullAnswer = prefix + answer + suffix
  prefix?: string    // text shown before the gap (continuation of original sentence)
  suffix?: string    // text shown after the gap
  answer: string     // the 2–5 word answer for the gap
  maxWords: number   // max words allowed (usually 5, per IELTS Use of English rules)
  explanation: string
  tip?: string
}

export const TRANSFORMATIONS: SentenceTransformation[] = [

  // ─── B1 ──────────────────────────────────────────────────────

  {
    id: 'b1_01',
    level: 'B1',
    category: 'passive',
    original: 'Someone stole my bicycle last night.',
    keyword: 'WAS',
    prefix: 'My bicycle',
    answer: 'was stolen',
    suffix: 'last night.',
    maxWords: 5,
    explanation: '"Someone stole my bicycle" → passive: "My bicycle was stolen (by someone)". Subject becomes the object; verb → was/were + past participle.',
    tip: 'Passive: was/were + past participle',
  },
  {
    id: 'b1_02',
    level: 'B1',
    category: 'reported_speech',
    original: '"I will call you tomorrow," he said.',
    keyword: 'PROMISED',
    prefix: 'He',
    answer: 'promised to call',
    suffix: 'me the next day.',
    maxWords: 5,
    explanation: '"I will call you" in direct speech → "promised to call me" in reported speech. Will → would, but with "promise to" we use infinitive.',
    tip: 'promise to + infinitive',
  },
  {
    id: 'b1_03',
    level: 'B1',
    category: 'conditionals',
    original: 'Study harder or you will fail the exam.',
    keyword: 'UNLESS',
    prefix: 'You will fail the exam',
    answer: 'unless you study',
    suffix: 'harder.',
    maxWords: 5,
    explanation: '"Or you will fail" = "unless you study harder". UNLESS = IF NOT. "Unless" introduces the condition that must be met to avoid the result.',
    tip: 'unless = if not',
  },
  {
    id: 'b1_04',
    level: 'B1',
    category: 'comparatives',
    original: 'No other city in the country is as expensive as London.',
    keyword: 'MOST',
    prefix: 'London is',
    answer: 'the most expensive city',
    suffix: 'in the country.',
    maxWords: 5,
    explanation: '"No other...is as X as Y" = "Y is the most X". Superlative replaces the comparative "as...as" structure.',
    tip: 'as expensive as → the most expensive',
  },
  {
    id: 'b1_05',
    level: 'B1',
    category: 'modal_verbs',
    original: 'It is not necessary for you to attend the meeting.',
    keyword: 'HAVE',
    prefix: "You don't",
    answer: 'have to attend',
    suffix: 'the meeting.',
    maxWords: 5,
    explanation: '"It is not necessary for you to" = "You don\'t have to". DON\'T HAVE TO means no obligation — very different from MUST NOT (prohibition).',
    tip: "don't have to = no obligation",
  },
  {
    id: 'b1_06',
    level: 'B1',
    category: 'gerund_infinitive',
    original: 'She regrets not studying for the test.',
    keyword: 'WISHES',
    prefix: 'She',
    answer: 'wishes she had studied',
    suffix: 'for the test.',
    maxWords: 5,
    explanation: '"Regret not doing" expresses past regret → "wish + past perfect" (had studied). Wish + past perfect for regret about the past.',
    tip: 'regret not doing → wish + had done',
  },
  {
    id: 'b1_07',
    level: 'B1',
    category: 'passive',
    original: 'They are building a new hospital near the station.',
    keyword: 'BEING',
    prefix: 'A new hospital',
    answer: 'is being built',
    suffix: 'near the station.',
    maxWords: 5,
    explanation: 'Continuous passive: is/are being + past participle. Present continuous active "are building" → "is being built".',
    tip: 'continuous passive: is being + past participle',
  },
  {
    id: 'b1_08',
    level: 'B1',
    category: 'phrasal_verbs',
    original: 'The meeting was postponed because of the bad weather.',
    keyword: 'PUT',
    prefix: 'The meeting',
    answer: 'was put off',
    suffix: 'because of the bad weather.',
    maxWords: 5,
    explanation: '"Postpone" = "put off". Both mean to delay until a later time. "Put off" must remain as phrasal verb in passive: was put off.',
    tip: 'postpone = put off',
  },

  // ─── B2 ──────────────────────────────────────────────────────

  {
    id: 'b2_01',
    level: 'B2',
    category: 'reported_speech',
    original: '"You should see a doctor," my mother told me.',
    keyword: 'ADVISED',
    prefix: 'My mother',
    answer: 'advised me to see',
    suffix: 'a doctor.',
    maxWords: 5,
    explanation: '"advise someone to do something" — reporting advice. "Should" in direct speech becomes "to + infinitive" after advise.',
    tip: 'advise + object + to + infinitive',
  },
  {
    id: 'b2_02',
    level: 'B2',
    category: 'conditionals',
    original: 'I didn\'t bring an umbrella, so I got wet.',
    keyword: 'IF',
    prefix: 'I',
    answer: 'would not have got',
    suffix: 'wet if I had brought an umbrella.',
    maxWords: 5,
    explanation: 'Third conditional: if + past perfect → would have + past participle. Describes an unreal past situation and its hypothetical result.',
    tip: 'Third conditional: would not have + pp',
  },
  {
    id: 'b2_03',
    level: 'B2',
    category: 'causative',
    original: 'A mechanic repaired my car yesterday.',
    keyword: 'HAD',
    prefix: 'I',
    answer: 'had my car repaired',
    suffix: 'yesterday.',
    maxWords: 5,
    explanation: 'Causative "have": have + object + past participle. Means you arranged for someone else to do something for you.',
    tip: 'have + object + past participle (causative)',
  },
  {
    id: 'b2_04',
    level: 'B2',
    category: 'inversion',
    original: 'She had no sooner arrived than the problems started.',
    keyword: 'SOONER',
    prefix: 'No',
    answer: 'sooner had she arrived',
    suffix: 'than the problems started.',
    maxWords: 5,
    explanation: '"No sooner...than" requires subject-auxiliary inversion: No sooner + had + subject + past participle. A formal structure expressing immediate sequence.',
    tip: 'No sooner + inversion (had + subject + pp)',
  },
  {
    id: 'b2_05',
    level: 'B2',
    category: 'relative_clauses',
    original: 'The report was written by a scientist. The scientist won a Nobel Prize.',
    keyword: 'WHO',
    prefix: 'The report was written by a scientist',
    answer: 'who won a Nobel',
    suffix: 'Prize.',
    maxWords: 5,
    explanation: 'Defining relative clause: "a scientist who won a Nobel Prize". WHO refers to a person and introduces the relative clause defining which scientist.',
    tip: 'who + defining relative clause for person',
  },
  {
    id: 'b2_06',
    level: 'B2',
    category: 'modal_verbs',
    original: 'I\'m sure he didn\'t take your book — he was at home all day.',
    keyword: 'HAVE',
    prefix: 'He can\'t',
    answer: "can't have taken",
    suffix: 'your book — he was at home all day.',
    maxWords: 5,
    explanation: '"Can\'t have + past participle" = deduction that something was impossible in the past. Logical impossibility based on evidence.',
    tip: "can't have + pp = impossible past deduction",
  },
  {
    id: 'b2_07',
    level: 'B2',
    category: 'comparatives',
    original: 'The more I practise, the better my English becomes.',
    keyword: 'IMPROVES',
    prefix: 'My English',
    answer: 'improves as I practise',
    suffix: 'more.',
    maxWords: 5,
    explanation: '"The more...the better" = a parallel improvement. Rewritten as: "My English improves as I practise more" using a simple adverbial clause.',
    tip: 'the more X, the more Y → Y improves as X increases',
  },
  {
    id: 'b2_08',
    level: 'B2',
    category: 'passive',
    original: 'People believe that the company will close next year.',
    keyword: 'BELIEVED',
    prefix: 'The company',
    answer: 'is believed to close',
    suffix: 'next year.',
    maxWords: 5,
    explanation: 'Impersonal passive: "It is believed that..." or "The subject is believed to...". Here: "The company is believed to close..." — formal, academic style.',
    tip: 'impersonal passive: is believed/thought/said to',
  },
  {
    id: 'b2_09',
    level: 'B2',
    category: 'inversion',
    original: 'I have never seen such an impressive performance.',
    keyword: 'NEVER',
    prefix: 'Never',
    answer: 'have I seen such',
    suffix: 'an impressive performance.',
    maxWords: 5,
    explanation: 'Negative adverb inversion: when "never" starts a sentence, invert subject and auxiliary. "Never have I seen" = emphatic, formal register.',
    tip: 'Never + auxiliary + subject (inversion)',
  },
  {
    id: 'b2_10',
    level: 'B2',
    category: 'gerund_infinitive',
    original: 'He denied that he had stolen the money.',
    keyword: 'DENIED',
    prefix: 'He',
    answer: 'denied having stolen',
    suffix: 'the money.',
    maxWords: 5,
    explanation: '"Deny + gerund": he denied having stolen. "Deny" is always followed by a gerund, not an infinitive. The gerund can be perfect: having + past participle.',
    tip: 'deny + having + past participle',
  },

  // ─── C1 ──────────────────────────────────────────────────────

  {
    id: 'c1_01',
    level: 'C1',
    category: 'inversion',
    original: 'The scientist only realised the significance of the discovery after years of analysis.',
    keyword: 'ONLY',
    prefix: 'Only after years of analysis',
    answer: 'did the scientist realise',
    suffix: 'the significance of the discovery.',
    maxWords: 5,
    explanation: '"Only after + time expression" triggers subject-auxiliary inversion: "Only after years of analysis did the scientist realise..." — emphatic formal structure.',
    tip: 'Only after + inversion (did + subject + base verb)',
  },
  {
    id: 'c1_02',
    level: 'C1',
    category: 'conditionals',
    original: 'If you hadn\'t helped me, I would never have finished the project.',
    keyword: 'BUT',
    prefix: 'I would never have finished the project',
    answer: 'but for your help',
    suffix: '.',
    maxWords: 5,
    explanation: '"But for + noun phrase" = "If it had not been for..." — a formal alternative to the third conditional. "But for your help" = if you hadn\'t helped.',
    tip: 'but for = if it had not been for (formal)',
  },
  {
    id: 'c1_03',
    level: 'C1',
    category: 'causative',
    original: 'The judge insisted that the evidence should be re-examined.',
    keyword: 'HAD',
    prefix: 'The judge',
    answer: 'had the evidence re-examined',
    suffix: '.',
    maxWords: 5,
    explanation: '"Have + object + past participle" = causative — the judge caused the re-examination to happen. Implies authority or arrangement.',
    tip: 'causative have: had + object + pp',
  },
  {
    id: 'c1_04',
    level: 'C1',
    category: 'relative_clauses',
    original: 'The professor gave a lecture. I found the lecture fascinating.',
    keyword: 'WHICH',
    prefix: 'The professor gave a lecture',
    answer: 'which I found fascinating',
    suffix: '.',
    maxWords: 5,
    explanation: 'Non-defining relative clause (or defining here): "a lecture which I found fascinating". WHICH refers to a thing; WHOM refers to a person as object.',
    tip: 'which + relative clause for things',
  },
  {
    id: 'c1_05',
    level: 'C1',
    category: 'modal_verbs',
    original: 'It was unnecessary for her to rewrite the entire report — a summary was enough.',
    keyword: 'NEEDN\'T',
    prefix: 'She',
    answer: "needn't have rewritten",
    suffix: 'the entire report — a summary was enough.',
    maxWords: 5,
    explanation: '"Needn\'t have + past participle" = it was not necessary to do something, but it was done. Different from "didn\'t need to" (which implies it wasn\'t done).',
    tip: "needn't have + pp = did it unnecessarily",
  },
  {
    id: 'c1_06',
    level: 'C1',
    category: 'reported_speech',
    original: '"Whatever you do, don\'t sign the contract before I return," the lawyer warned.',
    keyword: 'WARNED',
    prefix: 'The lawyer',
    answer: 'warned us not to sign',
    suffix: 'the contract before she returned.',
    maxWords: 5,
    explanation: '"Warn + object + not to + infinitive" — reporting a negative instruction. "Don\'t sign" → "warned us not to sign".',
    tip: 'warn + object + not to + infinitive',
  },
  {
    id: 'c1_07',
    level: 'C1',
    category: 'inversion',
    original: 'Hardly had the ceremony begun when it started to rain.',
    keyword: 'HARDLY',
    prefix: 'Hardly',
    answer: 'had the ceremony begun',
    suffix: 'when it started to rain.',
    maxWords: 5,
    explanation: '"Hardly had + subject + past participle + when..." = barely started when something else happened. Inversion required after "Hardly" at sentence start.',
    tip: 'Hardly had + subject + pp + when',
  },
  {
    id: 'c1_08',
    level: 'C1',
    category: 'comparatives',
    original: 'The economic situation is not as critical as many commentators suggest.',
    keyword: 'FAR',
    prefix: 'The economic situation is',
    answer: 'far less critical than',
    suffix: 'many commentators suggest.',
    maxWords: 5,
    explanation: '"Not as critical as" = "less critical than". "FAR less critical than" adds emphasis. "Far" intensifies comparative adjectives.',
    tip: 'far less + comparative + than (emphasis)',
  },
  {
    id: 'c1_09',
    level: 'C1',
    category: 'passive',
    original: 'Experts consider the painting to be one of the most valuable in the world.',
    keyword: 'REGARDED',
    prefix: 'The painting',
    answer: 'is regarded as one',
    suffix: 'of the most valuable in the world.',
    maxWords: 5,
    explanation: '"Regard as" in passive: "is regarded as...". This is the formal impersonal passive often used with consider, regard, view, see — always followed by "as".',
    tip: 'is regarded as (impersonal passive + as)',
  },
  {
    id: 'c1_10',
    level: 'C1',
    category: 'conditionals',
    original: 'Should you require any further assistance, please do not hesitate to contact us.',
    keyword: 'SHOULD',
    prefix: 'Should',
    answer: 'you require any further',
    suffix: 'assistance, please do not hesitate to contact us.',
    maxWords: 5,
    explanation: '"Should + subject + verb" = formal conditional inversion of "If you should require...". Used in formal correspondence instead of "if". No comma before "should" in this inversion.',
    tip: 'Should + subject + verb = formal "if" inversion',
  },
]
